/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 24-Sep-2017 5:40:26 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

USE `amt`
;

SET FOREIGN_KEY_CHECKS=0 
;

/* Create Tables */

CREATE TABLE `role`
(
	`role` VARCHAR(5) NOT NULL,
	`description` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_role` PRIMARY KEY (`role` ASC)
)

;

CREATE TABLE `users`
(
	`user_id` INT NOT NULL AUTO_INCREMENT,
	`user_name` VARCHAR(50) NOT NULL,
	`password` VARCHAR(50) NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`first_name` VARCHAR(15) 	,
	`last_name` VARCHAR(15) 	,
	`role` VARCHAR(5) NOT NULL,
	`is_active` BOOL NOT NULL,
	`creation_date` DATETIME NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`user_id` ASC),
	CONSTRAINT `FK_users_role` FOREIGN KEY (`role`) REFERENCES `role` (`role`) ON DELETE Restrict ON UPDATE Restrict
)

;

SET FOREIGN_KEY_CHECKS=1 
;
