/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 28-Oct-2017 3:58:58 AM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Create Tables */

CREATE TABLE `role`
(
	`role` VARCHAR(5) NOT NULL,
	`description` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_role` PRIMARY KEY (`role` ASC)
)

;

CREATE TABLE `user_ip_deactive`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`user_id` INT NOT NULL,
	`ip` VARCHAR(50) NOT NULL,
	`trail_num` INT NOT NULL,
	`last_trail_date` DATETIME NOT NULL,
	`is_active` BOOL NOT NULL,
	CONSTRAINT `PK_user_ip_deactive` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `user_ip_failure`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(50) NOT NULL,
	`ip` VARCHAR(50) NOT NULL,
	`login_date` DATETIME NOT NULL,
	CONSTRAINT `PK_user_ip_failure` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `user_login_log`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`user_id` INT NOT NULL,
	`ip` VARCHAR(50) NOT NULL,
	`login_date` DATETIME NOT NULL,
	`is_success` BOOL NOT NULL,
	`error_code` VARCHAR(10) 	,
	`error_msg` VARCHAR(150) 	,
	CONSTRAINT `PK_user_login_log` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `users`
(
	`user_id` INT NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(15) 	,
	`last_name` VARCHAR(15) 	,
	`user_name` VARCHAR(50) NOT NULL,
	`password` VARCHAR(50) NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`role` VARCHAR(5) NOT NULL,
	`creation_date` DATETIME NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`user_id` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `user_ip_deactive` 
 ADD CONSTRAINT `FK_user_ip_deactive_users`
	FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `user_login_log` 
 ADD CONSTRAINT `FK_user_login_log_users`
	FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `users` 
 ADD CONSTRAINT `FK_users_role`
	FOREIGN KEY (`role`) REFERENCES `role` (`role`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
