SET SQL_SAFE_UPDATES=0;
DELETE FROM amt.course_reference;
DELETE FROM amt.course_pre_requisite;
DELETE FROM amt.section;
DELETE FROM amt.course;
DELETE FROM amt.content_status;
DELETE FROM amt.course_level;
DELETE FROM amt.course_type;
DELETE FROM amt.material_type;
DELETE FROM amt.system_parameter;
DELETE FROM amt.data_type;
DELETE FROM amt.user_ip_deactive;
DELETE FROM amt.user_ip_failure;
DELETE FROM amt.user_login_log;
DELETE FROM amt.users;
DELETE FROM amt.role;