INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000001PrIn20161102', 'Bachelor of Nursing', 'In', 'Pr', 'Fu', '64', 'Adipiscingpersecuti himenaeos detracto possit vituperatoribus fabellas id nisi iaculis labores has nulla id litora suspendisse contentiones senserit vestibulum.  Consequatlegere deserunt sodales primi', '8', '1297', '2016-11-02 08:33:36', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000002AcIn20161102', 'Master of Psychology', 'In', 'Ac', 'Fu', '63', 'Laciniadicunt erat senserit nec amet facilisis dicunt legimus mediocritatem ultricies neque quisque mazim sumo wisi latine nam evertitur.  Habemuspersequeris mea dissentiunt interesset omnesque invidu', '5', '1297', '2016-11-02 08:33:36', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000003AcIn20161101', 'Bachelor of Health Science', 'In', 'Ac', 'Fu', '36', 'Leopretium lectus tristique similique conceptam perpetua convallis quas volumus ubique imperdiet eruditi vituperata habemus oporteat honestatis porro ligula.  Quaequenecessitatibus error aliquid vis m', '7', '1297', '2016-11-01 08:33:36', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000004PrAd20171006', 'Master of Criminology', 'Ad', 'Pr', 'Fu', '14', 'Crasvelit sollicitudin te utamur mus integer discere vocibus vituperatoribus decore.  Suscipitepicurei vivendo vulputate vehicula aptent mea dui definitionem.  Sadipscingerror aliquet fuisset cursus. ', '10', '812', '2017-10-06 04:37:37', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000005AcAd20171002', 'Associate Degree in Design', 'Ad', 'Ac', 'Fu', '20', 'Noutroque a equidem saepe cum viverra.  Persecutisociosqu maiorum sem nonumes etiam patrioque nobis labores est cetero convallis tamquam sed homero at nunc his audire posse.  Habeoreformidans nominavi', '14', '812', '2017-10-02 04:37:37', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000006AcAd20161202', 'Bachelor of Law', 'Ad', 'Ac', 'Fu', '25', 'Honestatisaptent lacinia fermentum sociosqu ligula postea ei ultrices class laoreet cubilia interesset neglegentur ullamcorper vocibus consequat agam appareat expetendis.  Euripidiselit risus eget cra', '11', '562', '2016-12-02 11:42:50', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000007AcBe20170418', 'Master of Teaching', 'Be', 'Ac', 'Fu', '43', 'Dictumstveritus pro reprimique tale ridiculus vel conclusionemque eirmod bibendum comprehensam.  Voluptariavel semper elementum dictum feugiat numquam ultricies alienum magna liber esse persius volupt', '7', '934', '2017-04-18 07:25:53', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000008PrBe20170417', 'Master of Medicine', 'Be', 'Pr', 'Fu', '24', 'Urbanitassolet utroque eu torquent feugait honestatis periculis facilisi posuere mucius agam option ridiculus maluisset eleifend sapientem platea pertinax.  Persecutielaboraret sociis pericula nonumes', '8', '934', '2017-04-17 07:25:53', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000009PrAd20170421', 'Master of Architectural Technology', 'Ad', 'Pr', 'Fu', '95', 'Duisjusto electram nostrum consequat veri interesset dicam audire oporteat.  Dicantbrute adversarium animal mnesarchum quo fusce elitr qui dapibus eos arcu facilisi.  Nullamdeserunt idque signiferumqu', '13', '934', '2017-04-21 07:25:53', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000010PrAd20170412', 'Bachelor of Design', 'Ad', 'Pr', 'Fu', '13', 'Minimdictum adhuc ius mutat tritani molestie aeque quaeque penatibus pharetra arcu signiferumque in veri tempus natoque.  Putentvehicula mazim efficiantur nulla sit cu deterruisset noster putent dolor', '11', '1325', '2017-04-12 12:51:12', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000011PrIn20170413', 'Master of Teaching', 'In', 'Pr', 'Fu', '83', 'Persequerisconvallis sodales hinc taciti quaeque vituperata mentitum eum class cum tractatos has aliquid accumsan.  Alienumaltera aliquid est lorem quo option pertinacia prompta parturient menandri me', '9', '1325', '2017-04-13 12:51:12', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000012PrAd20170414', 'Bachelor of Engineering', 'Ad', 'Pr', 'Fu', '9', 'Verisem veritus condimentum offendit et decore facilis mollis torquent aeque parturient molestie eirmod dignissim hinc mel.  Nonumypossim morbi conubia his morbi doctus quaerendum in imperdiet esse qu', '11', '1970', '2017-04-14 03:27:49', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000013PrIn20170413', 'Associate Degree in Design', 'In', 'Pr', 'Fu', '60', 'Dolorumfelis nominavi purus tortor.  Vimad autem graeci pellentesque ultricies legere persius elitr ut definiebas omittam autem.  Saperetpersequeris voluptatum auctor delenit dolores ipsum ludus numqu', '7', '1970', '2017-04-13 03:27:49', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000014PrBe20170415', 'Bachelor of Biomedical Science', 'Be', 'Pr', 'Fu', '74', 'Doloremaliquam solum conclusionemque tacimates oratio omittam consul sagittis intellegat eius quam falli maiestatis luptatum maiorum vivamus quaeque dignissim.  Etiamarcu eu tritani mediocritatem ius ', '10', '1970', '2017-04-15 03:27:49', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000015AcAd20170416', 'Associate Degree in Architectural Technology', 'Ad', 'Ac', 'Fu', '42', 'Homerooporteat homero justo inani rhoncus utamur lacinia tractatos tacimates definitiones pretium alia fermentum litora voluptatibus orci.  Affertdicit omnesque doming reformidans tractatos bibendum a', '7', '1970', '2017-04-16 03:27:49', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000016PrBe20170918', 'Master of Biomedical Science', 'Be', 'Pr', 'Fu', '48', 'Pertinaxhonestatis at.  Convenireatomorum sociis taciti lacus hinc fugit doctus.  Nontristique dolores.  
Rutrummalorum porro erroribus suscipiantur mus aenean qualisque saperet laoreet nobis antiopam', '13', '577', '2017-09-18 03:45:11', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000017AcBe20170919', 'Bachelor of Education', 'Be', 'Ac', 'Fu', '53', 'Affertrecteque persius nisl percipit ludus autem dolorum ocurreret eloquentiam viris est adipiscing eirmod nam primis mel donec detraxit signiferumque.  Fuscemontes iudicabit quod sociis alienum eius ', '5', '577', '2017-09-19 03:45:11', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000018PrIn20170919', 'Bachelor of Psychology', 'In', 'Pr', 'Fu', '85', 'Hisfacilisi mutat volumus delicata senectus accusata rhoncus massa explicari metus tincidunt scelerisque vivendo parturient fastidii.  Erroribusdictumst ocurreret eget iudicabit.  Dolorhimenaeos posue', '14', '577', '2017-09-19 03:45:11', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000019AcAd20170910', 'Master of Psychology', 'Ad', 'Ac', 'Fu', '87', 'Quovidisse quam luctus inciderint hinc percipit ornatus eget.  Saperetlaudem volutpat quam viderer vehicula mazim nobis euripidis inciderint ex mucius arcu vero venenatis.  Dictaaliquip fastidii est a', '5', '345', '2017-09-10 10:35:01', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000020PrAd20170307', 'Bachelor of Engineering', 'Ad', 'Pr', 'Fu', '47', 'Repudiandaecurae sem.  Nostrabrute definiebas tota impetus ea dui inceptos diam harum necessitatibus quis persecuti libero possit urbanitas pulvinar.  Voluptatibusrepudiare sanctus postulant quaestio.', '12', '630', '2017-03-07 08:58:13', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000021PrAd20170311', 'Bachelor of Education', 'Ad', 'Pr', 'Fu', '93', 'Maecenasoporteat appareat errem suavitate ut aenean gravida taciti mandamus veri fusce sale magna.  Crassapientem delectus eius doctus postea neque epicurei platea fringilla dolor convenire nascetur t', '7', '630', '2017-03-11 08:58:13', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000022PrAd20170722', 'Master of Architectural Technology', 'Ad', 'Pr', 'Fu', '50', 'Elitcongue conceptam aliquam ridiculus noluisse nihil mollis partiendo.  Vituperataqui prompta quaerendum numquam hac verterem omnesque cetero consetetur indoctum vituperata semper gravida dolor errem', '5', '791', '2017-07-22 03:17:44', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000023PrIn20170721', 'Associate Degree in Information Systems', 'In', 'Pr', 'Fu', '31', 'Omittamquo simul.  Mentitumpossit assueverit elaboraret enim molestie.  Similiqueinimicus vocent neque consetetur euismod eget sententiae tibique vidisse sumo iriure odio odio sumo.  Nominaviurna utin', '7', '791', '2017-07-21 03:17:44', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000024AcAd20170723', 'Associate Degree in Applied Science (Psychology)', 'Ad', 'Ac', 'Fu', '40', 'Delectushinc nihil graeco vel debet labores donec detracto postulant posuere adolescens indoctum esse vituperata habemus debet et sententiae corrumpit.  Domingiudicabit repudiare tellus reprehendunt s', '10', '791', '2017-07-23 03:17:44', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000025AcBe20170315', 'Associate Degree in Communications', 'Be', 'Ac', 'Fu', '34', 'Accommodareconstituam hac suspendisse felis molestiae.  Brutehis imperdiet pharetra persequeris dictum parturient elaboraret dicat adipisci.  
Facilisiseos ligula error referrentur quaestio signiferum', '11', '909', '2017-03-15 12:31:06', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000026AcAd20170424', 'Associate Degree in Teaching', 'Ad', 'Ac', 'Fu', '72', 'Aptenthonestatis adolescens.  Deseruntindoctum posuere consequat dicunt bibendum minim mattis iuvaret dicit sonet veniam eam sagittis mutat dolore.  Singulisfacilis solum adversarium fames scelerisque', '12', '1739', '2017-04-24 06:53:34', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000027PrBe20170423', 'Associate Degree in Creative Arts', 'Be', 'Pr', 'Fu', '69', 'Doloressumo potenti mediocritatem comprehensam eos vocibus.  Atomorumsuavitate aliquip veritus ubique.  Maluissetridens conceptam nulla suspendisse praesent aliquip litora rutrum deterruisset maiestat', '10', '1739', '2017-04-23 06:53:34', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000028AcIn20171217', 'Bachelor of Design', 'In', 'Ac', 'Fu', '34', 'Convallislabores pro viris aeque legere vero scripta consectetur primis fames similique consectetur aliquet persecuti efficiantur.  Atquiviris laudem has erroribus.  Parturientprimis velit dictumst pr', '9', '1254', '2017-12-17 09:04:39', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000029PrBe20171214', 'Associate Degree in Psychology', 'Be', 'Pr', 'Fu', '75', 'Exmaiestatis tincidunt gloriatur leo.  Aliquetvituperatoribus gravida natum necessitatibus diam menandri molestie.  
Senectusiaculis malorum electram reprimique quot utroque mei viris mediocritatem di', '6', '1254', '2017-12-14 09:04:39', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000030PrBe20171213', 'Master of Teaching', 'Be', 'Pr', 'Fu', '62', 'Porroindoctum indoctum taciti tantas lacinia ceteros venenatis delenit gubergren autem platea graeci option cetero electram tempor.  Cunecessitatibus nonumy.  Oratioverear ornatus postea pericula plat', '12', '1254', '2017-12-13 09:04:39', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000031AcAd20171023', 'Bachelor of Medicine', 'Ad', 'Ac', 'Fu', '95', 'Movetpetentium convenire constituam te dignissim est sadipscing postulant maximus deserunt mus ludus venenatis reprehendunt elit sapien ridiculus molestie.  Muciusalienum quam integer porro electram n', '8', '528', '2017-10-23 02:13:05', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000032PrBe20171022', 'Master of Criminology', 'Be', 'Pr', 'Fu', '83', 'Porroius adolescens debet vituperatoribus saperet eirmod senectus nostra ridiculus vim suas periculis salutatus odio ocurreret ultrices inani.  Conclusionemquequot alienum suavitate reprehendunt suspe', '7', '528', '2017-10-22 02:13:05', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000033PrBe20171021', 'Bachelor of Law', 'Be', 'Pr', 'Fu', '89', 'Nullanumquam felis lacinia nascetur reprimique maximus has alia pertinacia graece reformidans wisi maluisset an utamur dicat tellus splendide delenit.  Iuvaretsenectus legere reprimique delectus adipi', '8', '617', '2017-10-21 09:44:52', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000034PrAd20171025', 'Bachelor of Arts', 'Ad', 'Pr', 'Fu', '35', 'Convenireinterdum id ocurreret tortor ius scripta massa vocibus meliore.  Pulvinarinciderint vitae ocurreret.  Risusscripserit nam iuvaret patrioque dui conceptam quas tibique utroque posuere vocent a', '10', '617', '2017-10-25 09:44:52', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000035PrBe20171025', 'Master of Biomedical Science', 'Be', 'Pr', 'Fu', '83', 'Adipiscingdonec iaculis risus litora duo tamquam menandri invenire partiendo mattis massa augue explicari molestiae parturient utinam.  Euripidisvidisse mea persius nisl malorum.  Vivendoutroque inter', '14', '617', '2017-10-25 09:44:52', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000036PrAd20170612', 'Associate Degree in Creative Arts', 'Ad', 'Pr', 'Fu', '59', 'Indoctumpericulis vehicula sit.  Quodautem vituperatoribus alterum error orci patrioque laoreet graeco facilis vero causae tortor fringilla adhuc fusce tacimates pharetra labores.  
Velvulputate maies', '5', '1492', '2017-06-12 11:51:06', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000037PrBe20170614', 'Associate Degree in Education', 'Be', 'Pr', 'Fu', '11', 'Nobisnumquam senectus signiferumque nunc luctus risus cursus habemus prompta quaeque sociosqu sale quis an penatibus idque finibus graece tractatos.  Errornetus possit.  Detraxitdeterruisset lobortis ', '7', '1492', '2017-06-14 11:51:06', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000038AcBe20170616', 'Bachelor of Psychology', 'Be', 'Ac', 'Fu', '64', 'Possehimenaeos qualisque praesent similique epicurei lectus noster facilisis torquent quot sumo sapien dolorem congue doctus instructior vis posse.  Iuvaretaliquip principes possim oratio iaculis frin', '7', '1492', '2017-06-16 11:51:06', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000039AcAd20170613', 'Associate Degree in Design', 'Ad', 'Ac', 'Fu', '78', 'Imperdietdicat mazim lacus ac duo detraxit.  Nonumesaliquet iuvaret interdum sapientem ipsum accumsan eros natoque intellegat gloriatur postulant.  Velittortor expetendis elementum aeque velit ultrice', '8', '1492', '2017-06-13 11:51:06', '0.0');
