INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000001AcBe20161212', 'Associate Degree in Business', 'Be', 'Ac', 'Fu', '86', 'Arcubibendum graeco offendit mnesarchum reprehendunt nec adversarium atqui ullamcorper ea nulla duo vituperata.  Laboresmassa gravida habemus vitae solet splendide pertinax consectetuer quidam ubique ', '13', '5316', '2016-12-12 02:16:35', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000002AcBe20170418', 'Master of Biological Science', 'Be', 'Ac', 'Fu', '19', 'Mnesarchumefficiantur discere vituperata feugiat varius posse similique numquam tortor necessitatibus nascetur.  Intellegatpersequeris duo luctus mediocritatem semper volutpat electram aliquip impetus', '14', '2298', '2017-04-18 06:59:12', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000003AcIn20170420', 'Bachelor of Teaching', 'In', 'Ac', 'Fu', '20', 'Optionveritus maximus vel eget vim referrentur consequat vituperatoribus sententiae verear movet porro veritus tamquam platea.  Nihilcubilia ponderum.  Quosadipscing theophrastus ferri accumsan splend', '13', '2298', '2017-04-20 06:59:12', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000004PrAd20170422', 'Master of Engineering', 'Ad', 'Pr', 'Fu', '89', 'Dictumluctus iusto offendit magnis.  Justodui omittantur varius sagittis ludus hac adhuc quis sodales contentiones sea affert mutat.  Nectibique definiebas nostrum usu discere ad maecenas aeque pellen', '7', '2298', '2017-04-22 06:59:12', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000005PrIn20161124', 'Associate Degree in Business', 'In', 'Pr', 'Fu', '89', 'Mazimdolorem libero hendrerit definitionem.  Suscipianturmorbi partiendo.  Alterumprompta offendit.  Nuncnulla sit volutpat explicari euripidis dicat euismod.  
Curaea repudiandae turpis indoctum iriu', '13', '1844', '2016-11-24 01:12:54', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000006PrIn20170322', 'Associate Degree in Communications', 'In', 'Pr', 'Fu', '5', 'Adolescensfacilis indoctum brute vivamus efficitur phasellus varius docendi putent neque eius montes delenit varius quaeque.  Reprehenduntin pertinax suas convenire elaboraret vivendo indoctum mauris ', '5', '674', '2017-03-22 01:37:55', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000007AcAd20170324', 'Bachelor of Law', 'Ad', 'Ac', 'Fu', '47', 'Tristiqueomittam nullam.  Aperirimaluisset molestie invenire prompta amet elaboraret debet detracto luptatum.  Integersuspendisse euripidis scelerisque in vitae senectus quot luptatum ultrices neglege', '5', '674', '2017-03-24 01:37:55', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000008PrIn20170325', 'Master of Education', 'In', 'Pr', 'Fu', '28', 'Sonetlegere nominavi decore tacimates vitae tristique ludus repudiare augue aliquid quisque adipiscing id homero consequat ea impetus solum.  Mandamuspertinacia sapien percipit posuere falli lobortis ', '6', '674', '2017-03-25 01:37:55', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000009PrAd20171001', 'Master of Architectural Technology', 'Ad', 'Pr', 'Fu', '98', 'Viverravero eius habitant reprehendunt ullamcorper tation unum convenire dictumst curae posse torquent etiam aperiri.  Legerefalli definitionem orci.  Ancillaemalesuada delicata mus orci tellus sodale', '11', '3896', '2017-10-01 06:19:32', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000010AcIn20161213', 'Bachelor of Architectural Technology', 'In', 'Ac', 'Fu', '89', 'Accumsanmaximus semper ea netus senserit nibh suscipit dicta vituperatoribus fringilla eos iusto quas quaestio eleifend viderer parturient voluptatibus platonem.  Fringillaassueverit montes antiopam d', '8', '725', '2016-12-13 11:14:00', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000011AcIn20161214', 'Associate Degree in Psychology', 'In', 'Ac', 'Fu', '98', 'Singulisnostrum petentium.  Fabellasnatoque nobis sollicitudin sollicitudin magna contentiones.  Tinciduntconsul auctor iusto vis duis torquent melius conceptam menandri consectetur habemus curabitur ', '12', '725', '2016-12-14 11:14:00', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000012PrIn20161215', 'Bachelor of Criminology', 'In', 'Pr', 'Fu', '39', 'Eidefinitiones errem porro suscipiantur invidunt veri molestiae finibus neglegentur mauris interpretaris.  Luctusin sale unum sumo malesuada.  Montesnecessitatibus magna vidisse iudicabit voluptatum d', '7', '725', '2016-12-15 11:14:00', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000013PrIn20161211', 'Master of Design', 'In', 'Pr', 'Fu', '6', 'Meloption docendi dicam dolore persius offendit diam dictumst ocurreret singulis.  Morbirisus scripserit deserunt verterem quod etiam fabellas habitasse justo tempor aenean fames.  Fugithabeo duo brut', '10', '725', '2016-12-11 11:14:00', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000014PrBe20170523', 'Master of Biomedical Science', 'Be', 'Pr', 'Fu', '45', 'Eamconubia tibique definiebas pertinacia offendit necessitatibus alterum salutatus enim.  Adipiscingscripserit petentium mucius nibh scripta necessitatibus utamur sententiae eruditi.  Adversariumlegim', '6', '5981', '2017-05-23 09:46:23', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000015AcIn20170521', 'Associate Degree in Architectural Technology', 'In', 'Ac', 'Fu', '32', 'Interdumelaboraret malorum error sapien qualisque invidunt necessitatibus.  Scriptavulputate ius deterruisset vituperatoribus cursus epicurei luctus menandri aptent.  
Interdumrepudiandae quidam ac el', '9', '5981', '2017-05-21 09:46:23', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000016PrAd20161222', 'Master of Communications', 'Ad', 'Pr', 'Fu', '18', 'Acsigniferumque interdum equidem aenean est viverra.  Quopossim partiendo alia sadipscing aperiri.  Intellegebatadhuc noluisse vocibus intellegat quaestio elit consectetuer placerat magna.  Impetusmen', '14', '3238', '2016-12-22 01:27:46', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000017PrBe20161221', 'Master of Forensic Science', 'Be', 'Pr', 'Fu', '42', 'Corrumpitcubilia novum invenire quisque iriure interdum persius vivendo veri molestie ius civibus.  Pertinaciadefinitionem deserunt hendrerit quod pertinax dolores sodales repudiandae aliquip pericula', '8', '3238', '2016-12-21 01:27:46', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000018AcAd20161222', 'Master of Communications', 'Ad', 'Ac', 'Fu', '54', 'Etadolescens commodo has vix maecenas ridens sea idque interesset recteque mediocritatem erroribus sed gubergren.  Dignissimfames fermentum maecenas invenire tritani ocurreret tristique alterum vestib', '8', '3238', '2016-12-22 01:27:46', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000019AcAd20161220', 'Master of Computer Science', 'Ad', 'Ac', 'Fu', '38', 'Autemneque conclusionemque intellegat aptent ad ridens adipiscing esse aliquip.  Conceptamexpetendis cu sociis duis eirmod.  Esseappareat pri nihil qui percipit lectus signiferumque ex egestas sagitti', '13', '3238', '2016-12-20 01:27:46', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000020PrIn20170411', 'Master of Business', 'In', 'Pr', 'Fu', '20', 'Rectequemolestie laoreet vivendo facilis verear brute ultrices civibus reformidans novum accommodare.  Harumdissentiunt putent theophrastus petentium necessitatibus agam vituperatoribus disputationi n', '8', '4816', '2017-04-11 04:57:32', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000021AcIn20170407', 'Master of Medicine', 'In', 'Ac', 'Fu', '76', 'Ridensdictas inani metus deterruisset ornatus eros te mea unum maiestatis eum nostra possim deterruisset verear utroque conubia.  Maiestatisvituperatoribus vis aenean id ignota varius principes etiam ', '8', '4816', '2017-04-07 04:57:32', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000022AcAd20170407', 'Master of Forensic Science', 'Ad', 'Ac', 'Fu', '19', 'Gubergrendolore fringilla morbi eros.  Velquam constituam reprehendunt ceteros interesset his convallis urna nominavi sem in causae netus quot cum at movet.  Sodalesaffert torquent vivamus sea laudem ', '5', '4816', '2017-04-07 04:57:32', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000023AcAd20170408', 'Master of Criminology', 'Ad', 'Ac', 'Fu', '92', 'Aptenteloquentiam an contentiones dicant senectus nonumes viverra fames.  Delectusnecessitatibus iusto signiferumque persecuti suavitate persius eloquentiam dignissim definitiones aliquet graece variu', '10', '4816', '2017-04-08 04:57:32', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000024PrAd20171024', 'Bachelor of Health Science', 'Ad', 'Pr', 'Fu', '16', 'Nonhac tale fabulas tractatos latine.  Plateamel interesset.  Deterruissetscripserit efficitur falli condimentum verterem aliquet solet ridens commune theophrastus ornare class postulant.  Quaestiocra', '12', '881', '2017-10-24 05:29:20', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000025PrAd20171022', 'Bachelor of Law', 'Ad', 'Pr', 'Fu', '92', 'Maluissetmel eleifend hendrerit partiendo numquam harum.  Vivendoluctus perpetua deserunt efficiantur tempus tamquam ornatus turpis.  Sollicitudintristique aperiri minim ludus saperet est litora sanct', '13', '881', '2017-10-22 05:29:20', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000026AcIn20171213', 'Bachelor of Criminology', 'In', 'Ac', 'Fu', '10', 'Convenireantiopam solum fames.  Necmutat fermentum.  Feugiatregione iriure mentitum vulputate animal inani condimentum proin potenti velit quot mus dolorem discere sapien ligula pellentesque ornare li', '10', '4012', '2017-12-13 05:19:29', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000027AcAd20171216', 'Associate Degree in Engineering', 'Ad', 'Ac', 'Fu', '71', 'Maurisscripta mei cum appetere.  Latinequem ponderum repudiare malorum simul litora placerat labores condimentum tamquam.  Electrampersius voluptatibus conubia sodales solum mediocritatem quam sea qui', '5', '4012', '2017-12-16 05:19:29', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000028AcBe20171216', 'Master of Health Science', 'Be', 'Ac', 'Fu', '67', 'Pellentesquedefinitiones no constituto vulputate efficiantur congue tota magnis quisque conceptam persius urna sententiae.  Massaconvallis mea assueverit convenire option postea dicat mi lacus apparea', '9', '4012', '2017-12-16 05:19:29', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000029PrIn20170819', 'Bachelor of Law', 'In', 'Pr', 'Fu', '76', 'Fabellasinvenire postea nibh suscipit erroribus discere singulis ad.  Posuereauctor adversarium maluisset eleifend eripuit moderatius pharetra convenire ullamcorper aliquip interdum purus felis incept', '9', '2397', '2017-08-19 06:29:17', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000030PrBe20170110', 'Bachelor of Biological Science', 'Be', 'Pr', 'Fu', '66', 'Vulputateconstituto posidonium nisl vivendo feugait animal constituto.  Ornarepossim sociosqu omnesque voluptatum gubergren.  
Errorpostulant facilisis mediocritatem vidisse auctor.  Adolescenspersecu', '8', '356', '2017-01-10 08:55:57', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000031AcAd20170110', 'Associate Degree in Teaching', 'Ad', 'Ac', 'Fu', '88', 'Conubiadelicata accommodare pertinax altera scripserit legere epicuri mutat.  Talequod nisl.  Exmagnis nominavi taciti quot feugait hendrerit luptatum metus graece vero altera.  Scripseritvero evertit', '6', '356', '2017-01-10 08:55:57', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000032PrAd20170408', 'Bachelor of Law', 'Ad', 'Pr', 'Fu', '94', 'Sonetmaecenas dictas duis alienum intellegebat eos expetenda atqui interpretaris noster habitant repudiare menandri saepe.  Nibhturpis fastidii.  Fallitibique senectus dis mel electram noluisse vocibu', '10', '861', '2017-04-08 08:47:22', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000033AcBe20170411', 'Master of Business', 'Be', 'Ac', 'Fu', '92', 'Expetendasenectus legimus sapientem nostra tacimates vituperatoribus deseruisse dis maximus.  Efficiturponderum suscipiantur.  Priantiopam neque nostra nostra etiam velit posse efficitur arcu solum re', '13', '861', '2017-04-11 08:47:22', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000034PrIn20170912', 'Associate Degree in Biomedical Science', 'In', 'Pr', 'Fu', '73', 'Percipitoption error vituperatoribus phasellus te nonumes libris elit amet no perpetua invidunt persequeris imperdiet conubia in commodo hendrerit suavitate.  Diamquot comprehensam ludus appetere vitu', '6', '4515', '2017-09-12 05:05:43', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000035PrIn20170912', 'Associate Degree in Education', 'In', 'Pr', 'Fu', '55', 'Unumfusce risus auctor conclusionemque sollicitudin veritus convenire sapien adversarium habemus.  Facilisiludus commodo graeco equidem laudem placerat hinc maiorum laoreet noster.  Gravidatacimates p', '13', '4515', '2017-09-12 05:05:43', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000036AcIn20170914', 'Master of Computer Science', 'In', 'Ac', 'Fu', '70', 'Accommodareputent adipisci explicari sententiae fames interpretaris pulvinar esse detraxit instructior senserit ridens mediocritatem constituto reprehendunt.  Oporteatelaboraret tristique meliore inte', '14', '4515', '2017-09-14 05:05:43', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000037PrAd20170628', 'Associate Degree in Health Science', 'Ad', 'Pr', 'Fu', '77', 'Homeroinani porro facilis sociis quis vestibulum oratio persequeris quo mollis principes donec postea et novum tractatos risus.  Lobortisconsequat ocurreret tincidunt laudem delectus quot commune prod', '9', '5734', '2017-06-28 03:38:30', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000038PrIn20170629', 'Bachelor of Forensic Science', 'In', 'Pr', 'Fu', '60', 'Midignissim voluptatibus detraxit maximus interpretaris gubergren constituam arcu appetere vituperatoribus suscipit pretium elitr placerat nihil facilisi vis.  Accumsanefficitur legimus efficitur mode', '11', '5734', '2017-06-29 03:38:30', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000039AcAd20170701', 'Associate Degree in Business', 'Ad', 'Ac', 'Fu', '58', 'Vituperatasenectus expetenda porttitor mediocritatem neque postulant mattis ligula persecuti dapibus vis aliquam partiendo.  Iustoauctor eruditi eius consul.  Fringillamolestie semper scripta non iriu', '14', '5734', '2017-07-01 03:38:30', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000040AcBe20170907', 'Associate Degree in Law', 'Be', 'Ac', 'Fu', '65', 'Vestibulumiriure nisl facilis et.  Pulvinariaculis nostrum himenaeos accommodare.  Partiendounum tristique singulis adipisci.  Quodissentiunt leo lorem dicant postea repudiandae veritus recteque nisl ', '7', '1266', '2017-09-07 02:11:27', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000041PrBe20171203', 'Master of Commerce', 'Be', 'Pr', 'Fu', '9', 'Convallisoratio lacus pertinacia posse.  Appareatgraecis idque cubilia alia lobortis ea varius saepe similique comprehensam feugiat.  Proinhomero dis iuvaret sale nulla movet voluptaria delicata omitt', '5', '4772', '2017-12-03 05:00:12', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000042PrBe20171203', 'Bachelor of Computer Science', 'Be', 'Pr', 'Fu', '21', 'Cumrecteque etiam ut nec potenti consetetur consetetur duis libero rhoncus dicta.  Velgraecis fames erroribus.  Purusiisque interesset tempus vim ullamcorper mnesarchum per regione ne animal signiferu', '7', '4772', '2017-12-03 05:00:12', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000043PrIn20171202', 'Master of Education', 'In', 'Pr', 'Fu', '82', 'Odiofabellas vulputate utroque.  Causaeiusto utamur alterum nostra litora contentiones comprehensam dignissim reque vulputate repudiandae viderer mentitum.  
Facilisvituperatoribus tation vocibus cont', '12', '4772', '2017-12-02 05:00:12', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000044AcBe20170320', 'Master of Biological Science', 'Be', 'Ac', 'Fu', '55', 'Ultricieserat graeci quaeque magnis dolores sententiae nihil ridiculus finibus porttitor turpis.  Nosterhis omnesque feugait imperdiet iriure scelerisque liber egestas sagittis instructior montes aper', '6', '1228', '2017-03-20 06:07:25', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000045AcIn20170218', 'Master of Teaching', 'In', 'Ac', 'Fu', '28', 'Virisrecteque aliquip saepe propriae.  Ornaredeseruisse ipsum wisi corrumpit.  Integersale veri populo nam delenit montes vix definitiones.  Meliusconvenire faucibus perpetua hinc.  Agambrute splendid', '6', '5451', '2017-02-18 06:53:52', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000046AcIn20170221', 'Master of Medicine', 'In', 'Ac', 'Fu', '25', 'Possimferri contentiones dico iaculis convenire suscipiantur quo justo eu cursus velit verterem tale fermentum mauris solum sagittis ornare quis.  Ultricesbrute quaeque dictumst tellus lobortis adipis', '13', '5451', '2017-02-21 06:53:52', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000047PrAd20170218', 'Master of Biological Science', 'Ad', 'Pr', 'Fu', '50', 'Patrioquelaoreet moderatius congue definitionem repudiare porro tation cum ornare nisl ancillae interpretaris petentium gravida no regione.  Laciniaiaculis ne velit definiebas menandri docendi graece ', '5', '5451', '2017-02-18 06:53:52', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000048AcBe20170219', 'Master of Education', 'Be', 'Ac', 'Fu', '82', 'Audiremattis evertitur reque morbi volutpat aliquip vituperata usu id altera quam suscipit senserit constituam.  Meltractatos expetendis aperiri iuvaret omnesque odio dolorum reprimique dolore quem la', '13', '5451', '2017-02-19 06:53:52', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000049AcIn20171201', 'Associate Degree in Architectural Technology', 'In', 'Ac', 'Fu', '32', 'Repudiaread potenti ornare graeco.  Vocibusnoster potenti gloriatur iusto discere quo pretium feugait parturient placerat conceptam alienum montes conceptam ipsum velit.  Aliquidauctor dapibus urna mi', '11', '2645', '2017-12-01 06:08:07', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000050PrBe20171130', 'Bachelor of Forensic Science', 'Be', 'Pr', 'Fu', '43', 'Dicitgraecis hac viris.  Dicittristique definitionem affert moderatius curabitur magnis sollicitudin principes dicat eum vivamus euripidis aliquam.  Metusquo has porta sumo vocent deseruisse nonumes p', '14', '2645', '2017-11-30 06:08:07', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000051AcAd20171129', 'Associate Degree in Education', 'Ad', 'Ac', 'Fu', '10', 'Unumomnesque principes sanctus lacus tantas ornare pulvinar efficitur.  Gravidaquisque nostrum oporteat nostra scripta dictum potenti nostra brute consectetur dui lacinia similique laudem.  Comprehens', '6', '2645', '2017-11-29 06:08:07', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000052PrBe20170409', 'Associate Degree in Education', 'Be', 'Pr', 'Fu', '36', 'Malesuadareque euripidis auctor pericula aliquip atqui mediocrem meliore detracto has pri possit pretium quas necessitatibus his.  Elitmea nonumes ocurreret class legimus dicam tortor iriure liber cur', '6', '2246', '2017-04-09 06:34:43', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000053AcAd20170112', 'Bachelor of Forensic Science', 'Ad', 'Ac', 'Fu', '18', 'Melipsum est singulis urna quo inceptos oporteat consectetur.  Aliquidest suscipit errem consectetuer facilisis esse salutatus persecuti maluisset debet.  
Sodalesdecore voluptaria praesent nulla fall', '10', '3177', '2017-01-12 07:01:49', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000054PrAd20170110', 'Bachelor of Criminology', 'Ad', 'Pr', 'Fu', '28', 'Seddetraxit cum.  Consetetureos saperet erat nullam auctor vocibus mucius quidam vix splendide posidonium.  
Tacitisingulis offendit signiferumque corrumpit assueverit percipit auctor dignissim erat t', '9', '3177', '2017-01-10 07:01:49', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000055PrBe20170110', 'Bachelor of Design', 'Be', 'Pr', 'Fu', '81', 'Moderatiustantas vocent integer appetere fusce graeci blandit magnis pri agam eos numquam iusto tantas.  Nihileget ad ante magna eius platonem quem ei solet diam adolescens salutatus adipiscing duo ta', '11', '3177', '2017-01-10 07:01:49', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000056PrIn20170111', 'Associate Degree in Design', 'In', 'Pr', 'Fu', '21', 'Elaboraretmaecenas atomorum verterem cu pulvinar dicam sententiae fugit varius tellus vivamus.  Decoredeserunt ea cetero natoque bibendum fames labores.  Vitaeiudicabit dico ignota doming debet expete', '7', '3177', '2017-01-11 07:01:49', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000057AcIn20170919', 'Bachelor of Architectural Technology', 'In', 'Ac', 'Fu', '71', 'Vismandamus definitionem civibus suscipit idque.  Integerfacilis praesent brute ea morbi vituperatoribus sonet porro convenire sociosqu tellus tamquam te aliquet evertitur mnesarchum arcu.  Nesenectus', '7', '885', '2017-09-19 09:56:03', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000058PrBe20170917', 'Bachelor of Biomedical Science', 'Be', 'Pr', 'Fu', '60', 'Omittamfabulas ornatus habemus porro dolor.  Natoqueomittantur natoque singulis porta melius tortor suas ipsum conclusionemque ponderum tempor aliquid.  Adipiscingpulvinar his quaerendum salutatus fau', '14', '885', '2017-09-17 09:56:03', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000059AcIn20161209', 'Bachelor of Arts', 'In', 'Ac', 'Fu', '33', 'Erremsuscipit dapibus ad utinam praesent nisl no dicat delectus nominavi.  Inceptosvituperata duis bibendum mi sea fusce per eam usu.  Omittanturlabores pertinacia tale oporteat gravida commodo sceler', '12', '4939', '2016-12-09 01:37:36', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000060PrBe20161209', 'Master of Business', 'Be', 'Pr', 'Fu', '8', 'Salevoluptaria error.  Posidoniumexpetendis accommodare verear has nunc ligula mediocritatem sapien intellegebat rhoncus meliore quod instructior donec pulvinar inimicus platonem.  Maiorumdeserunt nos', '13', '4939', '2016-12-09 01:37:36', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000061AcIn20161209', 'Associate Degree in Computer Science', 'In', 'Ac', 'Fu', '28', 'Lacusbrute commune mediocrem gloriatur agam mel persius velit eros tacimates deterruisset vituperatoribus taciti.  Usuubique aptent his.  Erremnecessitatibus possim reformidans veritus efficitur fuiss', '6', '4939', '2016-12-09 01:37:36', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000062AcAd20161207', 'Master of Criminology', 'Ad', 'Ac', 'Fu', '80', 'Natoqueest menandri scripta eum verear tristique ornatus detracto urna purus mollis vulputate at graece veri percipit.  Sociosqumattis ad pellentesque commune ferri nibh prodesset option his intellege', '9', '4939', '2016-12-07 01:37:36', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000063PrIn20170721', 'Associate Degree in Criminology', 'In', 'Pr', 'Fu', '43', 'Sanctussuas aliquet ei sagittis fabulas.  Aliquamvivamus vocent pulvinar mnesarchum tibique viris.  Reformidansjusto convenire sed alia quem hinc propriae.  Dignissimfelis definiebas populo elitr indo', '6', '5086', '2017-07-21 04:05:28', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000064AcBe20170501', 'Master of Forensic Science', 'Be', 'Ac', 'Fu', '45', 'Mazimquam voluptatum morbi lorem dictas cras noster evertitur quaeque possim pericula indoctum gloriatur cetero persecuti doming his.  Veropersequeris signiferumque luctus conceptam postulant legimus ', '12', '3839', '2017-05-01 11:04:38', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000065AcAd20170428', 'Bachelor of Teaching', 'Ad', 'Ac', 'Fu', '14', 'Rhoncusdonec vero necessitatibus vestibulum metus posse dapibus meliore nascetur.  Nostraiisque inciderint.  Nasceturdictumst mutat euismod nonumes.  Melioretheophrastus senserit semper tritani recteq', '13', '3839', '2017-04-28 11:04:38', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000066PrBe20170430', 'Associate Degree in Communications', 'Be', 'Pr', 'Fu', '9', 'Maluissettristique porro labores.  Aliquamhabitant postulant meliore consectetuer saepe suspendisse.  
Donecenim efficiantur platonem mauris nihil ea honestatis epicuri populo deseruisse viverra purus', '14', '3839', '2017-04-30 11:04:38', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000067AcAd20170427', 'Master of Engineering', 'Ad', 'Ac', 'Fu', '9', 'Meiest dicta graecis brute definiebas nisl mazim rutrum phasellus reprehendunt sale atqui ridiculus.  Suavitateinstructior doctus maiorum nibh nihil omittantur ultricies viris efficiantur signiferumqu', '10', '3839', '2017-04-27 11:04:38', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000068AcIn20170909', 'Associate Degree in Medicine', 'In', 'Ac', 'Fu', '73', 'Epicureinatum error integer nam diam sonet atqui autem natoque senectus.  Audirepopulo eum eius no torquent maluisset adolescens malesuada mediocrem mandamus quo aliquam.  
Mazimvocent delenit aliquid', '12', '2451', '2017-09-09 08:07:57', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000069AcAd20170425', 'Bachelor of Information Systems', 'Ad', 'Ac', 'Fu', '73', 'Solummontes verear luptatum theophrastus.  Quaequegraecis convallis.  
Theophrastusmetus lectus adipiscing nulla.  Ametaltera reprehendunt percipit pretium vestibulum expetenda.  
Decorenam ligula dol', '9', '4068', '2017-04-25 12:33:36', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000070AcIn20170104', 'Associate Degree in Forensic Science', 'In', 'Ac', 'Fu', '76', 'Legimusferri sententiae ridens condimentum neglegentur persequeris epicurei ea vitae tritani cu deterruisset dicat indoctum.  Vitaevehicula possim sem malesuada gravida aptent qui lorem.  Nonumescu lu', '6', '5827', '2017-01-04 04:36:41', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000071AcBe20170107', 'Master of Applied Science (Psychology)', 'Be', 'Ac', 'Fu', '67', 'Fugitcomprehensam consetetur persequeris aliquip iaculis.  Eloquentiamrecteque viris definitionem saperet brute urna accommodare honestatis quis doming erroribus sed orci tale.  Nostrumpropriae erat i', '7', '5827', '2017-01-07 04:36:41', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000072PrBe20170217', 'Bachelor of Psychology', 'Be', 'Pr', 'Fu', '24', 'Euismodputent nisl congue autem similique sed lobortis.  Vocentaugue pulvinar pretium verterem posuere consectetuer constituam cras libris primis efficitur partiendo inceptos nulla fugit natum maluiss', '7', '799', '2017-02-17 10:22:48', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000073PrIn20170131', 'Bachelor of Information Systems', 'In', 'Pr', 'Fu', '24', 'Repudiaretempor volutpat mandamus idque expetenda purus risus ultrices blandit vituperatoribus reprehendunt persecuti sale scripta gloriatur hinc.  Atomorummalorum similique ea ante parturient efficit', '10', '3042', '2017-01-31 11:51:03', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000074PrIn20170129', 'Associate Degree in Criminology', 'In', 'Pr', 'Fu', '5', 'Eleifendaccumsan platonem.  Expetendaelitr parturient ridiculus expetenda.  Dictasconvenire etiam eius vix quam sapientem qualisque dui eloquentiam risus porta facilisi ubique cum postea brute aperiri', '9', '3042', '2017-01-29 11:51:03', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000075PrBe20170130', 'Associate Degree in Biomedical Science', 'Be', 'Pr', 'Fu', '61', 'Liberoalia inciderint.  Doloremconstituto congue homero nulla augue doctus necessitatibus tractatos autem esse doming usu per.  
Deseruissemalesuada tation ante doming veniam minim.  Autemsenserit eti', '7', '3042', '2017-01-30 11:51:03', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000076PrAd20170829', 'Bachelor of Computer Science', 'Ad', 'Pr', 'Fu', '26', 'Blanditnetus viris deterruisset agam quem fringilla ocurreret conceptam suscipit.  Mattisdicit offendit lectus maluisset delenit his porta esse condimentum ex elaboraret aeque vis erat eros cu no inte', '9', '2600', '2017-08-29 06:09:12', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000077PrIn20170718', 'Associate Degree in Commerce', 'In', 'Pr', 'Fu', '29', 'Erataccumsan nulla libero.  Gravidanec ligula graeci pro aliquip enim nibh graece id verterem himenaeos tincidunt proin volumus aeque consectetuer.  
Nullammalesuada pharetra voluptaria moderatius omn', '14', '2146', '2017-07-18 02:00:21', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000078AcAd20170717', 'Master of Psychology', 'Ad', 'Ac', 'Fu', '79', 'Dapibusinceptos prompta elementum detracto vidisse vocent velit harum sagittis sociis malorum at mazim suscipiantur voluptaria detraxit repudiandae.  Utsolum primis urbanitas simul veniam egestas eget', '6', '2146', '2017-07-17 02:00:21', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000079AcBe20170717', 'Associate Degree in Criminology', 'Be', 'Ac', 'Fu', '54', 'Dicantdetraxit suavitate disputationi neglegentur molestiae reprehendunt mollis simul pharetra reprehendunt sumo conubia postulant ullamcorper vis menandri eleifend instructior adipisci.  Hasvoluptati', '7', '2146', '2017-07-17 02:00:21', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000080PrAd20170717', 'Bachelor of Biomedical Science', 'Ad', 'Pr', 'Fu', '68', 'Aliquetrhoncus conclusionemque expetenda congue vis tellus vim impetus saepe fames.  Communesplendide ante liber fusce debet scripta dis eloquentiam adhuc libero consul pericula detraxit comprehensam ', '11', '2146', '2017-07-17 02:00:21', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000081PrAd20170322', 'Master of Education', 'Ad', 'Pr', 'Fu', '21', 'Quodsonet oratio.  Causaevidisse mauris quis sem graeci reprimique ceteros patrioque mauris legere scripta legere mei definitiones dis facilis invenire.  
Sedridiculus dignissim dicam semper platea.  ', '10', '3137', '2017-03-22 09:33:08', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000082AcIn20170324', 'Bachelor of Architectural Technology', 'In', 'Ac', 'Fu', '46', 'Verteremullamcorper luptatum tempor dicant adipiscing sumo ius appareat pericula ridiculus aptent reprimique.  Librisiusto simul eius fuisset postea noluisse vituperata adhuc lectus sadipscing tacimat', '14', '3137', '2017-03-24 09:33:08', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000083AcAd20171210', 'Bachelor of Engineering', 'Ad', 'Ac', 'Fu', '91', 'Oporteatdiscere civibus elementum autem semper vocent dapibus alienum porttitor dolores.  Torquentposidonium eloquentiam pretium aliquet intellegebat purus novum ponderum simul hac populo placerat ini', '7', '657', '2017-12-10 01:22:01', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000084AcIn20171210', 'Bachelor of Engineering', 'In', 'Ac', 'Fu', '41', 'Eloquentiamvarius possim necessitatibus neque tellus assueverit posse cras graeco.  Egetelementum percipit persius invenire causae appetere omittantur nostra pretium ad maximus aptent wisi elementum s', '11', '657', '2017-12-10 01:22:01', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000085PrIn20171208', 'Associate Degree in Biological Science', 'In', 'Pr', 'Fu', '23', 'Noluissewisi salutatus eirmod aperiri veritus natoque proin quod nulla impetus.  Etid eget parturient netus vidisse dolores gravida congue ornatus postulant ac evertitur.  Quoomnesque definitionem err', '8', '657', '2017-12-08 01:22:01', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000086PrAd20171201', 'Bachelor of Biological Science', 'Ad', 'Pr', 'Fu', '44', 'Prodesseteget eius.  Novumliber praesent appetere odio himenaeos efficitur consequat.  Gubergrenlacinia expetenda morbi ponderum aeque feugiat tota reprehendunt consul.  Discererutrum perpetua dictum ', '8', '4768', '2017-12-01 07:46:56', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000087AcIn20171202', 'Master of Arts', 'In', 'Ac', 'Fu', '33', 'Eratdeterruisset labores mazim ferri ius constituto vulputate porro quam habitant.  Ponderumoption mi molestie conubia elaboraret sed.  Lobortispercipit signiferumque conubia tale comprehensam augue e', '6', '4768', '2017-12-02 07:46:56', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000088AcBe20161230', 'Bachelor of Education', 'Be', 'Ac', 'Fu', '22', 'Latinesententiae audire mus malesuada.  Gloriatureget ac dissentiunt lacus ridens eum ponderum definiebas explicari arcu consectetuer class gloriatur patrioque tempus.  
Tationquam ac elaboraret eius ', '11', '3264', '2016-12-30 06:45:25', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000089AcAd20161229', 'Bachelor of Communications', 'Ad', 'Ac', 'Fu', '66', 'Neglegenturdefinitiones harum adipisci eripuit mi tation simul tristique impetus usu quot eirmod esse.  Verihac altera detracto veritus putent electram pro postea diam ultrices risus.  Aliadicta pro d', '9', '3264', '2016-12-29 06:45:25', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000090AcAd20170102', 'Bachelor of Computer Science', 'Ad', 'Ac', 'Fu', '14', 'Feugaitgraeci ligula consequat no nostra option mus montes egestas dolores wisi justo est pri quem ullamcorper cum lorem.  Potenticonceptam mollis theophrastus malesuada.  Deterruissetpericulis omitta', '9', '3264', '2017-01-02 06:45:25', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000091PrIn20161224', 'Bachelor of Biomedical Science', 'In', 'Pr', 'Fu', '97', 'Vehiculaimperdiet conceptam evertitur mus neglegentur nam eripuit gloriatur repudiandae referrentur primis aenean civibus reprimique reprimique.  Dapibusscelerisque fugit rhoncus novum vituperata.  Ta', '5', '4239', '2016-12-24 07:20:56', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000092AcBe20171026', 'Master of Communications', 'Be', 'Ac', 'Fu', '99', 'Consuleius delicata pro rhoncus omnesque legimus atqui fuisset lorem nostrum solet aliquip populo tractatos nullam ornare mazim.  Nonumycurabitur sonet suscipit ei petentium solum blandit autem fermen', '8', '3173', '2017-10-26 03:05:40', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000093AcAd20171026', 'Bachelor of Business', 'Ad', 'Ac', 'Fu', '46', 'Mazimfames omittam nam voluptatibus.  Natumocurreret commune homero fermentum duis facilisi regione finibus donec voluptatibus menandri luptatum diam est semper minim alterum.  Agamvim eripuit hinc ea', '5', '3173', '2017-10-26 03:05:40', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000094PrIn20171027', 'Associate Degree in Business', 'In', 'Pr', 'Fu', '13', 'Cuminteger cu libero tritani senserit menandri diam graeco torquent imperdiet deseruisse constituam.  Comprehensamvel morbi aliquet facilis id quo nostra patrioque sociosqu disputationi curabitur aper', '6', '3173', '2017-10-27 03:05:40', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000095AcAd20171031', 'Bachelor of Computer Science', 'Ad', 'Ac', 'Fu', '10', 'Commodoiaculis deterruisset est percipit non graeci nostra oporteat omittantur est venenatis.  Dicooratio himenaeos efficiantur inceptos laudem.  
Placeratvolumus maecenas quaestio a aliquid dolores c', '9', '2972', '2017-10-31 01:08:20', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000096AcBe20171029', 'Master of Information Systems', 'Be', 'Ac', 'Fu', '37', 'Signiferumqueius ad ante ridiculus eget docendi efficitur graece delectus invidunt populo.  Rhoncusquisque te magna similique quisque persius.  Persequerisverterem appetere aptent qui tristique expete', '14', '2972', '2017-10-29 01:08:20', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000097AcIn20171029', 'Bachelor of Criminology', 'In', 'Ac', 'Fu', '25', 'Percipitvocent pretium natum necessitatibus libris.  Utregione cubilia sodales ludus libero hac ancillae legere doming arcu.  
Appetereanimal sagittis audire.  Consectetuerviderer putent orci curae na', '8', '2972', '2017-10-29 01:08:20', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000098PrBe20171030', 'Bachelor of Education', 'Be', 'Pr', 'Fu', '77', 'Ornatusfinibus deterruisset morbi ignota reprehendunt mediocritatem quo cubilia persius petentium montes urna ornatus movet erroribus solet tempor faucibus signiferumque.  Metusscripserit epicurei min', '14', '2972', '2017-10-30 01:08:20', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000099AcBe20170614', 'Bachelor of Engineering', 'Be', 'Ac', 'Fu', '20', 'Aliquideu conceptam bibendum deseruisse mediocrem luptatum tractatos vivendo sodales graeci scelerisque viderer electram.  Persecutiutamur maximus faucibus ex assueverit vivendo nisl movet interpretar', '9', '584', '2017-06-14 08:09:13', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000100PrBe20170615', 'Associate Degree in Biological Science', 'Be', 'Pr', 'Fu', '81', 'Exceteros explicari offendit molestie inceptos nonumes dictumst veri aliquip doctus leo postulant dis altera decore persius tation oratio quam.  Menandrireferrentur quisque periculis sonet electram ae', '8', '584', '2017-06-15 08:09:13', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000101PrIn20170615', 'Bachelor of Communications', 'In', 'Pr', 'Fu', '56', 'Signiferumquevoluptatum sodales feugiat ex fringilla.  Rhoncusconvenire nonumy epicuri fugit ante vim impetus.  Mollistristique erroribus porttitor voluptatum nisi ipsum id deterruisset disputationi. ', '10', '584', '2017-06-15 08:09:13', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000102AcAd20170614', 'Bachelor of Communications', 'Ad', 'Ac', 'Fu', '14', 'Definitionemtheophrastus discere habeo platea volumus non sententiae similique maiorum vis lacus.  Maecenasaliquam fugit.  Novumsapientem similique quod intellegat mollis libero pulvinar tellus.  Omne', '6', '584', '2017-06-14 08:09:13', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000103PrIn20171021', 'Bachelor of Health Science', 'In', 'Pr', 'Fu', '94', 'Quemipsum vix.  Vestibuluman dicat postea fugit homero primis vituperata conceptam dissentiunt senectus odio maximus honestatis delectus volumus dignissim movet.  Conseteturrepudiandae lectus neque ce', '13', '4498', '2017-10-21 08:54:00', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000104AcAd20171020', 'Associate Degree in Design', 'Ad', 'Ac', 'Fu', '90', 'Virisaltera curabitur facilis eruditi consetetur euripidis altera alterum magnis legere ut perpetua maximus doctus unum maluisset elementum maecenas.  Quoius decore nec ubique conubia rhoncus mel rutr', '7', '4498', '2017-10-20 08:54:00', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000105PrAd20171020', 'Master of Business', 'Ad', 'Pr', 'Fu', '65', 'Vidissesingulis legimus sadipscing eos habemus propriae mediocrem.  Utinammetus expetenda.  Regionelatine brute maximus consequat mentitum quisque iuvaret delenit accumsan id vidisse affert reprimique', '10', '4498', '2017-10-20 08:54:00', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000106AcBe20170911', 'Bachelor of Computer Science', 'Be', 'Ac', 'Fu', '97', 'Appetereaptent qualisque nisl dicant sodales dicam definitiones pellentesque proin.  Utsuspendisse sodales lorem convenire mei quas maecenas tractatos adipiscing tantas porta quaestio tempor erroribus', '11', '319', '2017-09-11 10:23:41', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000107PrIn20170915', 'Master of Architectural Technology', 'In', 'Pr', 'Fu', '9', 'Gloriaturno consectetuer audire suspendisse eos mei neglegentur maximus cras interdum an porro quas metus felis nostra mnesarchum adipiscing nostra.  Interessetconclusionemque duo expetenda justo ever', '11', '319', '2017-09-15 10:23:41', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000108AcIn20170912', 'Associate Degree in Education', 'In', 'Ac', 'Fu', '50', 'Aptentturpis blandit percipit sagittis habeo blandit porttitor persius tellus te veri nam.  Expetendisadipisci legere periculis hinc reformidans tantas posse menandri fusce sapientem tellus amet repud', '6', '319', '2017-09-12 10:23:41', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000109AcIn20171002', 'Master of Communications', 'In', 'Ac', 'Fu', '76', 'Tristiqueprompta hac splendide constituam.  Omittamdico an duis.  
Expetendisdis delectus semper velit constituto sanctus his.  Natoqueid sociis sumo scelerisque possit tempor velit blandit idque adip', '6', '948', '2017-10-02 03:12:37', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000110AcAd20171001', 'Master of Applied Science (Psychology)', 'Ad', 'Ac', 'Fu', '96', 'Indoctumgraecis dolores arcu maecenas deseruisse nisl animal quis esse solet cubilia quaestio delectus eu.  Ornatusposse ei cum graece molestie enim corrumpit mediocrem fames mi.  
Convallisfermentum ', '5', '948', '2017-10-01 03:12:37', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000111AcAd20171001', 'Master of Nursing', 'Ad', 'Ac', 'Fu', '94', 'Interdumscripta sapientem invenire agam sapientem omittam novum ullamcorper dictum accusata adipiscing.  Suscipitnisl vero.  Requeeum disputationi commune gloriatur utroque dolor fabellas causae cras ', '11', '948', '2017-10-01 03:12:37', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000112AcBe20171001', 'Associate Degree in Commerce', 'Be', 'Ac', 'Fu', '71', 'Urbanitasconstituam mazim maiestatis duo dolorem sapientem morbi mandamus.  Tristiquesollicitudin taciti sapien ullamcorper quis netus sapientem atomorum comprehensam luctus noster eruditi usu.  Offen', '7', '948', '2017-10-01 03:12:37', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000113AcBe20170301', 'Associate Degree in Health Science', 'Be', 'Ac', 'Fu', '62', 'Detractocivibus referrentur volumus viris eros.  Indoctumaliquam luptatum deterruisset mollis scripserit eleifend.  Laoreetpropriae dolores quas assueverit cursus tempor propriae fastidii pharetra alt', '8', '819', '2017-03-01 12:39:08', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000114AcIn20171220', 'Associate Degree in Medicine', 'In', 'Ac', 'Fu', '13', 'Famessociosqu sumo consectetuer posidonium potenti quo inimicus postulant imperdiet habeo.  Dolorumsingulis efficitur cu quod felis constituam mi invidunt proin turpis movet ponderum iudicabit.  Nostr', '9', '2692', '2017-12-20 01:34:35', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000115AcIn20171216', 'Bachelor of Health Science', 'In', 'Ac', 'Fu', '21', 'Senseritvero maluisset dictum similique dictumst hinc petentium neque tristique detraxit cursus efficitur tota noluisse.  Electramproin graeci affert verear netus nostra tation quot pertinax maiestati', '8', '2692', '2017-12-16 01:34:35', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000116PrIn20171216', 'Bachelor of Biomedical Science', 'In', 'Pr', 'Fu', '63', 'Essepericulis detraxit ancillae intellegat ad docendi qualisque solet arcu.  Tacitimagnis vehicula corrumpit maluisset discere consectetur legere tibique morbi aeque debet noster pri.  Eirmodgraecis t', '12', '2692', '2017-12-16 01:34:35', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000117AcAd20161204', 'Bachelor of Teaching', 'Ad', 'Ac', 'Fu', '58', 'Neglegenturdictum pellentesque ut usu varius conclusionemque percipit dictas quam mandamus feugiat quem alterum parturient errem lacinia eam instructior vel.  Idquenullam pellentesque porro assueverit', '12', '2618', '2016-12-04 11:54:22', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000118AcIn20170916', 'Bachelor of Commerce', 'In', 'Ac', 'Fu', '14', 'Egetmalorum constituam utamur numquam aptent petentium reformidans dolor audire persecuti eget.  Musnoluisse dicat platea partiendo tale mediocritatem sociis quod omnesque meliore fermentum erroribus ', '5', '1120', '2017-09-16 01:45:50', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000119PrBe20170917', 'Bachelor of Education', 'Be', 'Pr', 'Fu', '69', 'Nullaminim autem.  Eilaoreet parturient.  Saperetaccusata novum minim bibendum platea omittam auctor an electram detraxit no simul gravida iaculis eius vituperata.  Eamutroque meliore molestiae suavit', '11', '1120', '2017-09-17 01:45:50', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000120PrIn20170914', 'Master of Architectural Technology', 'In', 'Pr', 'Fu', '92', 'Quaestioverterem dolor adhuc errem.  Ignotadefiniebas simul inciderint mi ocurreret tempor.  
Alacinia maximus metus parturient voluptatibus.  Verituspericula referrentur tortor potenti explicari sens', '8', '1120', '2017-09-14 01:45:50', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000121PrIn20170917', 'Master of Creative Arts', 'In', 'Pr', 'Fu', '60', 'Vixfalli rutrum mus volumus assueverit per per saperet elit.  Pertinaxdelicata adipiscing salutatus sociosqu fastidii verterem voluptatum habeo quis tristique quo ne adipisci corrumpit graece posidoni', '11', '1120', '2017-09-17 01:45:50', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000122PrBe20170524', 'Associate Degree in Communications', 'Be', 'Pr', 'Fu', '80', 'Dapibushabemus cum prodesset reprehendunt mutat deterruisset phasellus habeo nisl phasellus has tota vitae ignota eius quod erroribus.  Reprimiquepulvinar dolor sollicitudin his quis accommodare qui l', '13', '5254', '2017-05-24 07:10:02', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000123AcAd20170522', 'Master of Biological Science', 'Ad', 'Ac', 'Fu', '32', 'Montessententiae quo ei convenire postea.  Nobisiaculis nobis theophrastus adversarium torquent netus alienum pellentesque porta putent legere graece imperdiet.  Maziminvidunt consectetuer hendrerit m', '5', '5254', '2017-05-22 07:10:02', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000124PrBe20170523', 'Bachelor of Biological Science', 'Be', 'Pr', 'Fu', '21', 'Dissentiunteu aptent orci alterum wisi elementum noluisse dignissim nobis.  Splendidecausae curabitur discere fastidii quaestio pericula torquent falli conubia habemus nobis nullam hendrerit ridens la', '10', '5254', '2017-05-23 07:10:02', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000125AcAd20170526', 'Associate Degree in Design', 'Ad', 'Ac', 'Fu', '93', 'Ponderummus conclusionemque usu labores labores pulvinar mazim solet expetenda litora option singulis omittantur recteque lobortis contentiones.  Accumsanmalorum esse sociosqu periculis honestatis fug', '6', '5254', '2017-05-26 07:10:02', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000126AcAd20171127', 'Master of Medicine', 'Ad', 'Ac', 'Fu', '52', 'Erroribusbibendum quas mucius class dictumst sed tamquam eirmod ludus offendit venenatis quaeque nunc lectus fusce an audire.  Iisquevocent blandit varius invidunt ei errem posse nostrum lacinia.  Vol', '7', '146', '2017-11-27 08:29:20', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000127AcAd20161223', 'Associate Degree in Business', 'Ad', 'Ac', 'Fu', '44', 'Duisapientem sagittis doming constituam enim dicam tractatos voluptatum.  Menandrimaiorum tibique eripuit aliquip.  Possealienum egestas postulant comprehensam massa civibus.  Singulisdolorem reprehen', '6', '1661', '2016-12-23 01:43:30', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000128AcBe20161222', 'Bachelor of Health Science', 'Be', 'Ac', 'Fu', '31', 'Simulreferrentur persius dolore dapibus ocurreret vitae interesset iisque gubergren mus eu sem neque libero quisque tota tempus elitr.  Attheophrastus equidem tation dicat saperet erat ac wisi mus et ', '9', '1661', '2016-12-22 01:43:30', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000129PrIn20161225', 'Associate Degree in Business', 'In', 'Pr', 'Fu', '34', 'Contentionessodales nam vivamus atqui iuvaret nonumes antiopam ferri.  Sapientemiriure nam auctor tellus fugit est labores tantas conceptam iusto luctus reformidans tamquam aliquip principes eloquenti', '9', '2631', '2016-12-25 10:33:41', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000130AcIn20161227', 'Bachelor of Applied Science (Psychology)', 'In', 'Ac', 'Fu', '48', 'Urbanitasnullam possim fusce errem nibh magnis.  Nononumy senserit sale nunc utinam.  Interpretarisdolorem inani option.  Splendideante sociosqu platea tota inani prompta movet pericula conubia nisi. ', '13', '2631', '2016-12-27 10:33:41', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000131AcAd20161225', 'Master of Design', 'Ad', 'Ac', 'Fu', '10', 'Inimicusdetracto ne tritani propriae disputationi pertinax corrumpit rutrum alia commune.  Nihileum moderatius luctus torquent alia dolorum fabulas vix integer ea ante ornatus risus ludus mus congue e', '12', '2631', '2016-12-25 10:33:41', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000132AcBe20161229', 'Bachelor of Engineering', 'Be', 'Ac', 'Fu', '64', 'Civibusinciderint alienum volumus vim aliquet tractatos posse amet fuisset indoctum vivamus scripta per iuvaret etiam fames nostra.  Haceuismod oporteat varius alterum faucibus adhuc nonumes tation ta', '14', '2631', '2016-12-29 10:33:41', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000133PrBe20170102', 'Associate Degree in Psychology', 'Be', 'Pr', 'Fu', '83', 'Orcimolestie habemus velit.  Consecteturmi dicam propriae vituperata noster aptent fringilla regione minim magna facilisis menandri.  Latineregione sollicitudin ponderum habitant sociis voluptatibus u', '14', '1446', '2017-01-02 04:26:01', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000134PrAd20170102', 'Bachelor of Engineering', 'Ad', 'Pr', 'Fu', '99', 'Doctustaciti option quem cras dolor pellentesque fastidii deserunt sodales.  Aequelacus consul augue.  Interdumnostrum posuere noster aptent at justo lobortis pro aenean quaeque theophrastus populo in', '13', '1446', '2017-01-02 04:26:01', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000135AcAd20170101', 'Master of Architectural Technology', 'Ad', 'Ac', 'Fu', '74', 'Suscipianturmolestiae liber tincidunt morbi recteque lectus leo tation ultricies cum nisi quo.  Adolescensne erroribus scelerisque egestas hinc cu decore reprehendunt integer voluptatibus populo accom', '7', '1446', '2017-01-01 04:26:01', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000136AcBe20170718', 'Bachelor of Communications', 'Be', 'Ac', 'Fu', '23', 'Evertiturea eius ultricies augue fuisset.  Ancillaepertinacia maecenas patrioque discere aptent suscipiantur inceptos definitiones maecenas vituperatoribus possit ius proin falli viderer omnesque.  
A', '8', '3873', '2017-07-18 04:39:53', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000137AcIn20170721', 'Master of Education', 'In', 'Ac', 'Fu', '77', 'Mazimurbanitas cras ancillae quod autem iaculis dicam cu agam natoque.  Causaegloriatur porro adipiscing persius laudem ludus lorem dicat primis lacinia.  Habitassefalli platea reformidans natum.  Mov', '12', '3873', '2017-07-21 04:39:53', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000138PrBe20170720', 'Bachelor of Communications', 'Be', 'Pr', 'Fu', '41', 'Tinciduntludus efficiantur veritus delectus bibendum ferri libris lacinia appareat suspendisse quam.  Loremharum mediocritatem turpis accumsan mediocritatem melius his tibique sale mus finibus euripid', '13', '3873', '2017-07-20 04:39:53', '0.0');
INSERT INTO course (course_id, course_name, course_level, course_type, course_status, estimated_duration, description, min_per_day, created_by, creation_date,  progress) VALUES ('Cor0000139AcBe20170718', 'Bachelor of Teaching', 'Be', 'Ac', 'Fu', '60', 'Iudicabitpopulo sed has gloriatur varius civibus regione solum laudem vis felis nostrum impetus sapien primis a impetus.  Atquivoluptatibus vix repudiare metus fusce velit mentitum dicunt disputationi', '8', '3873', '2017-07-18 04:39:53', '0.0');
